sudo: required
dist: trusty
services:
- docker
language: c
install:
- docker run --name builder -e LC_ALL=en_US.UTF-8 -v $PWD:$PWD -w $PWD -td ubuntu:xenial
- docker exec -i builder locale-gen en_US.UTF-8
- docker exec -i builder sed -i s/archive.ubuntu.com/us.archive.ubuntu.com/g /etc/apt/sources.list
- docker exec -i builder dpkg --add-architecture i386
- docker exec -i builder apt update
- docker exec -i builder sh -c "apt install -y snapcraft build-essential git"
script:
- docker exec -i builder snapcraft
before_deploy:
- mkdir results
- docker cp builder:$PWD/pharo-vm_6.0_amd64.snap results/pharo-vm_6.0_amd6_`git describe --always`.snap
- ls -l
- "./scripts/deploy_bintray_prepare.sh"

deploy:
  provider: bintray
  file: ".bintray.json"
  user: guillep
  key:
    secure: lN15/VIBljt6zGGxghbXLhVhWxXb63d15/wVkgg36atpRsziOE0BkVzKDO6JtxNxRhBsaXsE4+u/eKhkJxwzRFTDXgwYClubyJJjLvVjCLW8oIgJe434aUPWjZW3IPeTTMLdZJO35q0CCZCT6udxq6SITvvbQMQ5wFf5lXBpcsVQEciJQho5USh82hS0OxSoKVRb4Knhy3AYioJ9S1XMBViYvMg4OZ0a0HrQSXfI/46u0bGzilUTpwDqg2xa4Mttn/Sa7j0swaIUTijBtYreSKSad+QoMreJpl3cukG7LnlnYQhnSqVrcAMIwKdUaIkCbCjRXJatB29aAbjoWYXpTrxEAIRaouPVclolqnUZIxQJzKw2iXg0rOufNGdTK73yvq23U8+3Q062/FzI1foWwppSz7q4Q6CIP0HKbJOrD2y9Fme0okW9jbhp/4KxIZrJRSX7nIlfMwefI1Fi+hI0YOnaWZZNYDlxo7gFNryCLabiC8i45HaraUGb44yPpY1ToCCOu2XHS26r+VAYk8IyAJmcq8/8R7s9CUxd7/zdSjgQOKIUP4U0GImnnwoW4932UpysxvV2Z8vUdpRTxxRq7HeNM8uK72EDTr2T95zJ12JU4nbhwNUEwf65Hz5oWBZCladk247J3VGmxHZwK7yjq9el+YgCsYf5ZPAjwKVttEQ=
  on:
    all_branches: true
