name: pharo-vm
version: 6.0
grade: devel
summary: Pharo Virtual Machine
description:
  Virtual machine for the Pharo language (www.pharo.org).
  You will need a pharo image file to be run with the vm.
confinement: devmode

apps:
  pharo-vm:
    command: results/pharo --nodisplay
  pharo-ui:
    command: results/pharo

parts:
  pharo-vm:
    plugin: pharo-build-plugin
    source: https://github.com/pharo-project/pharo-vm.git
    source-type: git
    source-depth: 1
    build-packages: ["gcc-multilib", "libssl-dev:i386","libssl1.0.0:i386","libfreetype6-dev:i386","libasound2-dev:i386","libsm-dev:i386","libgl1-mesa-dev:i386","libx11-dev:i386","libice-dev:i386", "wget", "unzip"]
  pharo-sources:
    plugin: dump
    source: http://files.pharo.org/sources/PharoV50.sources.zip
    source-type: zip
